
WHITESPACE = _{ (" " | "\t") }
COMMENT = _{"#" ~ (!NEWLINE ~ ANY)* ~ &NEWLINE}
LINE = _{NEWLINE ~ WHITESPACE* ~ COMMENT?}
EOL = _{LINE+}
EOL0 = _{ LINE* }

name = @{ (ASCII_ALPHANUMERIC|"_")+ }

field = {
    name ~ name
}

def = { name ~ "{" ~ EOL ~ (field ~ EOL)* ~ "}"}
link_n = @{
    ("1"|"n") ~ ("?")?
}
ARROW_BODY = {("=" | "-")+}
link = {
    name ~ link_n ~ ARROW_BODY ~ link_n ~ name ~ (":" ~ name)?
}

document = {
    EOL0 ~ ((def|link) ~ EOL)+ ~ EOI
}

